# pre-commit-config.yaml

repos:
  # Python linters and formatters
  - repo: https://github.com/psf/black
    rev: 23.7.0  # You can specify the version here
    hooks:
      - id: black
        name: black (python formatter)
        language_version: python3  # Ensure Python 3 is used

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Latest release at the time of writing
    hooks:
      - id: flake8
        name: flake8 (python linter)
        language_version: python3  # Ensure Python 3 is used

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Latest release
    hooks:
      - id: mypy
        name: mypy (python type checker)
        language_version: python3

  # Arduino .ino file checks
  - repo: local
    hooks:
      - id: arduino-lint
        name: arduino-lint
        entry: arduino-cli lint --warnings all  # Command to run Arduino CLI lint
        language: system
        files: \.ino$

  # Optional: trailing whitespace checks for all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
